### ISSUE TITLE
Misspelled Field Name

### ISSUE THREAD

**Issue by chris-rowe** [hamiltop/rethinkdb_ecto#5]
File: connection.ex
Line # 97
Issue:The filed name is currently spelled updateed_at
Fix: change to updated_at in order to perform correct queries on that field

Very small issue, but otherwise great work that is benefiting the community!
Thanks!

**Comment by hamiltop** [comment]
Pull request?

**Comment by hamiltop** [comment]
@pwnerzclub Thanks for finding this. Sorry about the terse response.

**Comment by chris-rowe** [comment]
No worries.  I was going to do a PR, but had to run out for work and didn’t want to forget about it.  Sorry
